[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LiveServer = "16fef848-5104-11e9-1b77-fb7a48bbb589"
OCPPData = "96fa3b67-1af3-5f07-99a6-8e4efc5edabb"
OCPPServer = "676c5a51-a8ef-5385-87a6-11d0f7ce946f"

[compat]
Documenter = "1"

[sources]
OCPPData = {url = "https://github.com/JuliaSolarPV/OCPPData.jl"}
OCPPServer = {path = ".."}
